### ISSUE TITLE
Review all supported blocks in Notion

### ISSUE THREAD

**Issue by aalemayhu** [alemayhu/Notion-to-Anki#117]
We have support for many of them due to the way we are working with HTML but that does not mean all of them. So we need to compile a list and go through it all.

**Comment by scanf** [comment]
Related-to: #87

**Comment by aalemayhu** [comment]
Will handle this in Notion https://www.notion.so/alemayhu/Feature-parity-with-Notion-d693054c328f404a9267d78681a75bef
