### ISSUE TITLE
sorting bug

### ISSUE THREAD

**Issue by aalemayhu** [alemayhu/Notion-to-Anki#139]
Tiffany reported that the sorting is messed up when importing. The order from Notion is not being perserved. This can be easily reproduced on existing profiles but does not always happen for new profiles. I need to investigate it.

**Comment by guillem-palau-salva** [comment]
I tried to reproduce this issue unsucessfully. I think this issue is not related to notion2anki. My best guess is that the user is not aware of the default decks group settings in different profiles. Please tell her to make sure she has order cards by creation time instead of random.

**Comment by aalemayhu** [comment]
- [ ] TODO: Read genanki sorting code

**Comment by aalemayhu** [comment]
Things have changed substantially since last time if this is still an issue. A new reproducer is needed.
