### ISSUE TITLE
move all of the user facing text into markdown files

### ISSUE THREAD

**Issue by aalemayhu** [alemayhu/Notion-to-Anki#14]
We already have a module for handling markdown and the having the text in the markup is getting really ugly. Also translation can be easier with the markdown files.

**Comment by scanf** [comment]
@guillem-palau-salva would it make it easier for translation if the text were in Markdown?

**Comment by guillem-palau-salva** [comment]
Sure, I just did it the other day with Anki manual which is in markdown as well.

**Comment by scanf** [comment]
Cool, I will look into this later and reach out. Thanks.

**Comment by aalemayhu** [comment]
I have decided to instead move more of the text into Notion itself.
