### ISSUE TITLE
Link back to Notion page

### ISSUE THREAD

**Issue by aalemayhu** [alemayhu/Notion-to-Anki#201]
This is from Twitter 
![image](https://user-images.githubusercontent.com/925044/95825304-f0887c80-0d30-11eb-9617-a0fb3fb2a187.png)

**Comment by aalemayhu** [comment]
My reply

> Hei there,

> We can add support for this, Notion uses ids for their pages. 

> I have created a issue for next week. So it’s part of the week 43 milestone.

> I like the idea, thanks for the suggestion 🙏🏾

**Comment by aalemayhu** [comment]
It is possible and we can use the filename but for now we don't want that kind of interaction with the client / server.

**Comment by aalemayhu** [comment]
We can maybe add this in a future release when our server / client interaction is better defined.

**Comment by andrewcrook** [comment]
May be Notions API can help when it is released?

**Comment by aalemayhu** [comment]
This is coming to the next deployment. Take a look at the proposal below and let me know if it makes sense or visible enough.

<img width="1920" alt="Screenshot 2021-07-08 at 9 52 13 PM" src="https://user-images.githubusercontent.com/925044/124982515-12e8c580-e037-11eb-836b-8338f228497d.png">
<img width="612" alt="Screenshot 2021-07-08 at 9 50 22 PM" src="https://user-images.githubusercontent.com/925044/124982522-154b1f80-e037-11eb-92ba-4129eda5c352.png">
<img width="1920" alt="Screenshot 2021-07-08 at 9 49 48 PM" src="https://user-images.githubusercontent.com/925044/124982524-15e3b600-e037-11eb-9f2e-26fa1c42c0ea.png">
