### ISSUE TITLE
When importing an inline equation as cloze

### ISSUE THREAD

**Issue by 100lewi** [alemayhu/Notion-to-Anki#250]
When importing an inline equation as cloze
![image](https://user-images.githubusercontent.com/1654416/108619803-88a51980-7427-11eb-9412-4200b90ff513.png)

HTML export
[Export-6f87f74f-070d-4ded-865c-a3c5f821be6c.zip](https://github.com/alemayhu/Notion-to-Anki/files/6017396/Export-6f87f74f-070d-4ded-865c-a3c5f821be6c.zip)

Notion page
https://www.notion.so/Issue-865d61f73a8e43f38da02f0097aa9ad3

**Comment by aalemayhu** [comment]
I will look into it, thanks for the example!

**Comment by aalemayhu** [comment]
This has now been resolved on the dev-server, special thanks to @Maximus0000 for fixing it.
https://dev.2anki.net/

Reference: https://github.com/alemayhu/Notion-to-Anki/pull/259
