### ISSUE TITLE
Font size 

### ISSUE THREAD

**Issue by Jadeasln** [alemayhu/Notion-to-Anki#258]
Hi, 

I just noticed that my font size changed on Anki, and although I'm choosing the smallest one on the website, I can't get the font on anki to size down 

Do you have any idea how to fix this ?

**Comment by aalemayhu** [comment]
Hei there!

I am aware of the issue and was hoping to get it resolved earlier.  Hopefully a fix is coming this weekend.

Thanks for reporting this.

**Comment by Jadeasln** [comment]
Thank you for the reply and once again for the website ! 

Best of luck for the days ahead :)

**Comment by aalemayhu** [comment]
Second-pass review (pm): User-requested feature with relevant code but no confirmed implementation

Evidence: code in: web/scripts/prerenderLandingPages.ts
web/src/pages/OpsPage/charts/timeSeriesChar

**Comment by aalemayhu** [comment]
Duplicate of #556 (Multi-column layouts collapse into one column). Consolidating there.
