### ISSUE TITLE
Persist Options in Local Storage

### ISSUE THREAD

**Issue by jerichocalibuso** [alemayhu/Notion-to-Anki#267]

**Comment by aalemayhu** [comment]
Hei there!

Which browser are you using? When have you experienced it not working?
Save me time by sharing your exact steps to reproduce.

Thanks!

**Comment by jerichocalibuso** [comment]
Hi!

I am using Brave browser. It happens when I simply refresh or revisit the page. Only the "Treat Strikethrough as Tags", "Basic Front and Back", and "Cloze Deletion" do not persist, other settings seem to work fine.

**Comment by aalemayhu** [comment]
That should be fixed on the DEV server now. Can you confirm before we deploy it? 
Here is the direct link https://dev.2anki.net/upload?view=template <https://dev.2anki.net/upload?view=template>

The explanation helped, thanks!

- -
Mit freundlichen Grüßen 

Alexander Alemayhu

YouTube: http://youtube.com/c/alexanderalemayhu <http://youtube.com/c/alexanderalemayhu>
Twitch: http://twitch.tv/alexanderalemayhu <http://twitch.tv/alemayhu>
Twitter: https://twitter.com/aalemayhu <https://twitter.com/aalemayhu>
More Links: https://links.alemayhu.com <https://links.alemayhu.com/>

**Comment by jerichocalibuso** [comment]
Thank you for the quick fix and for this app!
