### ISSUE TITLE
Create an official add-on for notion2anki

### ISSUE THREAD

**Issue by aalemayhu** [alemayhu/Notion-to-Anki#53]
From Discord 

```
Alpīnus Kānus Axuus:
Maybe you could create an add-on that works with notion2anki
Just create a deck with it (using the url)
And add-on checks if the notion page is changed
In case it is changed, it creates an updated deck and replaces it with the current deck
```

**Comment by balta2ar** [comment]
This is actually a great idea. I'll probably go my own old-fashioned way and I'll put it into my crontab, but if you're interested, I botched up a crude and simple Notion exporter: https://github.com/balta2ar/srs-toolbelt/blob/master/yatetradki/notion2anki/notion.py
Feel free to use it, adapt, modify, etc.

**Comment by aalemayhu** [comment]
While it would be interesting, I am personally not so interested in making add-ons for the current Anki infrastructure. I will be exploring other ways to create add-ons, so moving this into a potential v2.0.0. 

Do you have any experience writing Anki add-ons?
- -
Mit freundlichen Grüßen 

Alexander Alemayhu

YouTube: http://youtube.com/c/alexanderalemayhu <http://youtube.com/c/alexanderalemayhu>
Twitter: https://twitter.com/aalemayhu <https://twitter.com/aalemayhu>
Twitch: http://twitch.tv/alemayhu <http://twitch.tv/alemayhu>

**Comment by balta2ar** [comment]
No, not really. I only have experience ripping apart Anki addons in a brutal and crude way to serve my needs of automation, which is miles away from having a nice reusable design :sweat_smile:

**Comment by aalemayhu** [comment]
I am actually playing around with the idea of creating a new web framework that is specialised for Anki add-ons creation.
This is something I will myself use for our add-on, the current state of affairs is a joke.

- -
Mit freundlichen Grüßen 

Alexander Alemayhu

YouTube: http://youtube.com/c/alexanderalemayhu <http://youtube.com/c/alexanderalemayhu>
Twitter: https://twitter.com/aalemayhu <https://twitter.com/aalemayhu>
Twitch: http://twitch.tv/alemayhu <http://twitch.tv/alemayhu>

**Comment by aalemayhu** [comment]
This is not the way.
