### ISSUE TITLE
New Option: flatten decks (merging multiple decks into one deck)

### ISSUE THREAD

**Issue by aalemayhu** [alemayhu/Notion-to-Anki#57]
Would be nice to have this option. It also related to subdecks.

Related-to: alemayhu/notion2anki#4

**Comment by scanf** [comment]
https://github.com/kerrickstaley/genanki/blob/7bb21120ce85be7bb017e3502a6da0c3098fc9f2/genanki/package.py#L12-L19

**Comment by aalemayhu** [comment]
While I would love to support merging, it's a little bit too complex for now. Let's do this in a major release.

**Comment by aalemayhu** [comment]
We support for subpages so this is no longer a issue.

**Comment by aalemayhu** [comment]
This is still an issue, try uploading multiple files and see what happens. Also pick a custom deck name.
[Export-4921fa12-6e78-429e-91b5-5d9309656dc8.zip](https://github.com/alemayhu/notion2anki/files/5252004/Export-4921fa12-6e78-429e-91b5-5d9309656dc8.zip)
[Export-b88e2479-fbca-480c-b941-38cb09124491.zip](https://github.com/alemayhu/notion2anki/files/5252005/Export-b88e2479-fbca-480c-b941-38cb09124491.zip)

**Comment by aalemayhu** [comment]
While this is something, I would love to have. We are moving this out of v1.

**Comment by aalemayhu** [comment]
Maybe call this `flatten decks`.

**Comment by aalemayhu** [comment]
While nice to have this is out of scope and nobody has really been asking for this.

**Comment by aalemayhu** [comment]
Reopening after triage: Flatten/merge decks option is a real product feature and a common ask; no explicit decline.. Reviewed by: pm agent.

**Comment by aalemayhu** [comment]
Closing — already implemented. Deck flattening/merging logic exists in `src/lib/anki/getDeckname.ts` with `::` notation for nested decks.
