### ISSUE TITLE
Add better icons

### ISSUE THREAD

**Issue by aalemayhu** [alemayhu/Notion-to-Anki#91]
We can use new ones or make more use of font-awesome.

https://heroicons.dev

**Comment by scanf** [comment]
I don't know what I think about this. What do you think @Mobilpadde?

**Comment by Mobilpadde** [comment]
I approve of heroicons :+1:

**Comment by aalemayhu** [comment]
While nice, let's defer this to 2.0.

**Comment by aalemayhu** [comment]
I think we will just use some custom SVG files. Don't want to add an extra dependency 😄

**Comment by aalemayhu** [comment]
Second-pass review (pm): TODO/stub found in relevant code - feature not fully implemented

Evidence: node_modules/.pnpm/@types+better-sqlite3@7.6.13/node_modules/@types/better-sqlite3/index.d.ts:3:// FIXME: Is this `any`

**Comment by Mobilpadde** [comment]
6 years 😂🫡

**Comment by aalemayhu** [comment]
@Mobilpadde long time no speak 👍🏾 The PM agent is working and commenting on my behalf. Never to late to update!

**Comment by aalemayhu** [comment]
Closing as part of stale-issue triage. 'Add better icons' has no concrete scope or acceptance criteria — which icons, on which surfaces, replacing what. Open-ended cosmetic churn isn't actionable as written. Re-open with a specific list (surface + current icon + desired icon/library) and it can be scoped and shipped.
